// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ynonkdzachhpgynbkuck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlub25rZHphY2hocGd5bmJrdWNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMTQ1MzMsImV4cCI6MjA3MzU5MDUzM30.PA27pD57PZ8hnMpZKecirbKkKafhnn9ZaBDBAJ1f6ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});